<!DOCTYPE html>
<html>
<head>
    <title>Activity Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f5f5f5; font-weight: bold; }
        .footer { margin-top: 30px; font-size: 10px; color: #777; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>WFH Pulse Activity History</h1>
        <p>Report Generated: {{ now()->format('M d, Y h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Employee</th>
                <th>Username</th>
                <th>Date</th>
                <th>Start - End</th>
                <th>Duration</th>
                <th>Allocated</th>
            </tr>
        </thead>
        <tbody>
            @foreach($logs as $log)
            <tr>
                <td>{{ $log->employee->name }}</td>
                <td>{{ $log->employee->username }}</td>
                <td>{{ $log->started_at->format('M d, Y') }}</td>
                <td>{{ $log->started_at->format('h:i A') }} - {{ $log->ended_at ? $log->ended_at->format('h:i A') : 'Active' }}</td>
                <td>{{ $log->duration_seconds ? gmdate('H:i:s', $log->duration_seconds) : 'Running' }}</td>
                <td>{{ $log->allocated_hours ? $log->allocated_hours . 'h' : '—' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by WFH Tracker System — &copy; {{ date('Y') }}
    </div>
</body>
</html>
